tap "beeftornado/rmtree"
tap "buo/cask-upgrade"
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "bat"
brew "cmake"
brew "deno"
brew "dust"
brew "exa"
brew "fzf"
brew "git"
brew "git-delta"
brew "git-extras"
brew "glow"
brew "htop"
brew "llvm"
brew "mas"
brew "n"
brew "neovim"
brew "ninja"
brew "pandoc"
brew "pkg-config"
brew "pygments"
brew "python@3.10"
brew "ripgrep"
brew "rustup-init"
brew "stow"
brew "tmux"
brew "trezor-bridge"
brew "vivid"
brew "wget"
brew "zola"
brew "zsh"
cask "cold-turkey-blocker"
cask "cron"
cask "discord"
cask "docker"
cask "drawio"
cask "firefox"
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro"
cask "hiddenbar"
cask "iterm2"
cask "mactex-no-gui"
cask "miniforge"
cask "netnewswire"
cask "notion"
cask "obsidian"
cask "raycast"
cask "shottr"
cask "trezor-suite"
cask "visual-studio-code"
cask "zoom"
cask "zotero"
mas "Dark Reader for Safari", id: 1438243180
mas "Drafts", id: 1435957248
mas "EasyRes", id: 688211836
mas "Flow", id: 1423210932
mas "Hush", id: 1544743900
mas "iMovie", id: 408981434
mas "Menu Bar Controller for Sonos", id: 1357379892
mas "one sec", id: 1532875441
mas "Overlap", id: 1516950324
mas "QuickShade", id: 931571202
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "Wipr", id: 1320666476
mas "Xcode", id: 497799835
