#!/bin/sh

read -p "Purge existing extentions?" yn
case $yn in
    [Yy]* ) rm -rf ~/.vscode/extensions; break;;
    [Nn]* ) echo "intalling alongside existing extentions";;
esac

while read x; do
    code --extensions-dir ~/.vscode/extensions --force --install-extension  $x
done < ./extensions.txt
